In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [9]:
df = pd.read_csv('../Input_features_1960.csv')
df = df.iloc[:,1:]
df.set_index('Month', inplace=True)
df

Fedfund_rate   GDP_pch  CPI_pc1  Loan_pch  House_ch
Month                                                          
1960-01-01          3.99  2.657590  1.24095      10.2    -197.0
1960-02-01          3.97  1.675410  1.41379      10.1    -164.0
1960-03-01          3.84  0.693230  1.51881       6.7    -511.0
1960-04-01          3.92 -0.288950  1.93237       6.6    -301.0
1960-05-01          3.85  0.086070  1.82507       3.3    -227.0
...                  ...       ...      ...       ...       ...
2023-05-01          5.06  1.310517  4.12884       6.0      40.0
2023-06-01          5.08  1.690863  3.09200       3.0    -143.0
2023-07-01          5.12  2.071210  3.29908       2.4      80.0
2023-08-01          5.33  2.071210  3.70750       6.3    -200.0
2023-09-01          5.33  2.071210  3.68990       4.4    -117.0

[765 rows x 5 columns]

In [15]:
from copy import deepcopy as dc
# 
def prepare_shifted_df(df, n_steps):
    df = dc(df)
    
    # df.set_index('Month', inplace=True)
    
    for i in range(1, n_steps + 1):
        df[f'Fedfund_rate(t-{i})'] = df['Fedfund_rate'].shift(i)
        
    df.dropna(inplace=True)
    
    return df

lookback = 3
shifted_df1 = prepare_shifted_df(df[['Fedfund_rate']], lookback)
shifted_df1

Fedfund_rate  Fedfund_rate(t-1)  Fedfund_rate(t-2)  \
Month                                                            
1960-04-01          3.92               3.84               3.97   
1960-05-01          3.85               3.92               3.84   
1960-06-01          3.32               3.85               3.92   
1960-07-01          3.23               3.32               3.85   
1960-08-01          2.98               3.23               3.32   
...                  ...                ...                ...   
2023-05-01          5.06               4.83               4.65   
2023-06-01          5.08               5.06               4.83   
2023-07-01          5.12               5.08               5.06   
2023-08-01          5.33               5.12               5.08   
2023-09-01          5.33               5.33               5.12   

            Fedfund_rate(t-3)  
Month                          
1960-04-01               3.99  
1960-05-01               3.97  
1960-06-01               3.84  
1960-07-01               3.92  
1960-08-01               3.85  
...                       ...  
2023-05-01               4.57  
2023-06-01               4.65  
2023-07-01               4.83  
2023-08-01               5.06  
2023-09-01               5.08  

[762 rows x 4 columns]

In [14]:
from copy import deepcopy as dc
# 
def prepare_shifted_df(df, n_steps):
    df = dc(df)
    
    # df.set_index('Month', inplace=True)
    
    for i in range(1, n_steps + 1):
        df[f'GDP_pch(t-{i})'] = df['GDP_pch'].shift(i)
        
    df.dropna(inplace=True)
    
    return df

lookback = 3
shifted_df2 = prepare_shifted_df(df[['GDP_pch']], lookback)
shifted_df2

GDP_pch  GDP_pch(t-1)  GDP_pch(t-2)  GDP_pch(t-3)
Month                                                         
1960-04-01 -0.288950      0.693230      1.675410      2.657590
1960-05-01  0.086070     -0.288950      0.693230      1.675410
1960-06-01  0.461090      0.086070     -0.288950      0.693230
1960-07-01  0.836110      0.461090      0.086070     -0.288950
1960-08-01  0.227070      0.836110      0.461090      0.086070
...              ...           ...           ...           ...
2023-05-01  1.310517      0.930170      1.131560      1.332950
2023-06-01  1.690863      1.310517      0.930170      1.131560
2023-07-01  2.071210      1.690863      1.310517      0.930170
2023-08-01  2.071210      2.071210      1.690863      1.310517
2023-09-01  2.071210      2.071210      2.071210      1.690863

[762 rows x 4 columns]

In [35]:
shifted1_np = shifted_df1.to_numpy()
shifted2_np = shifted_df2.to_numpy()
# shifted1_np.shape

X1 = shifted1_np
X2 = shifted2_np
assert(X1.shape == X2.shape)
print(f"X1 shape is {X1.shape}")
print(X1)
X = [X1, X2]
X = np.zeros([X1.shape[0], X1.shape[1], 2])

X[:,:,0] = X1
X[:,:,1] = X2
print(f"X shape is {X.shape}")
# plt.plot(X[:,:,0])
# plt.plot(X1)


X1 shape is (762, 4)
[[3.92 3.84 3.97 3.99]
 [3.85 3.92 3.84 3.97]
 [3.32 3.85 3.92 3.84]
 ...
 [5.12 5.08 5.06 4.83]
 [5.33 5.12 5.08 5.06]
 [5.33 5.33 5.12 5.08]]
X shape is (762, 4, 2)
